version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:14.0
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data # host volume
    networks:
      - database-starter

  mongo:
    container_name: mongo
    image: mongo:7.0
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo-data/:/data/db
    networks:
      - database-starter

  redis:
    container_name: redis
    image: redis:7.2.2-alpine3.18
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - ./redis-data/:/data
    networks:
      - database-starter

networks:
  database-starter:
    driver: bridge
