version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mypostgredb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data # host volume

  mongo:
    container_name: mongo
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: mymongodb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo-data/:/data/db
